# 部分配置项意义可见https://github.com/JetBrains/kotlin-playground
kotlin_playground:
  # 加载的额外js内容, 
  extend:
    # js: "source/_data/kotlin_playground.js"
  # 是否禁用插件
  disable_plugin: ~
  # 要引用的kotlin-playground的源
  src: 'https://unpkg.com/kotlin-playground@1'
  # playground的数据选择器,即为要选择的代码块标记,应当是符合querySelect的内容
  data_selector: '.kotlin-code'
  # 数据服务器,要请求的服务器地址,默认为~
  data_server: ~
  # 要使用的版本,默认为~(最新版)
  data_version: ~
  # 要生成的html标签名称
  html_tag: 'code'
  # 要生成的html标签带的类名,最好和data_selector想对应
  html_tag_class: 'kotlin-code'
  # 自定义的预配置
  custom_pre:
  # 自定义的代码块预配置
  custom_cb_pre: 
  # 是否启用行号,默认为true
  line_numbers: true
  # 是否启用自动缩进,默认为true
  auto_indent: true
  # 要将tab替换为的内容
  tab: '    '
  # 要缩进的长度
  indent: 4
  # 当前代码块的主题
  # 支持 idea|darcula|default
  theme: 'default'
  # 若非kotlin语言,则使用的其他的解析引擎,均为hexo-util内的解析方法
  # 支持 highlight|prismjs
  other_highlight: 'highlight'
  # 其他的解析引擎的配置
  other_highlight_config:
    # 禁用highlight.js的自动语言检测
    autoDetect: false
  # css配置,这里是为了统一代码块内样式的
  css:
    font_size: '20px'
    line_height: '25px'